### PR TITLE
Removes Whitelist for Police/AI. Removes player age restriction for antags.

### PR DESCRIPTION
**Pull request by Redrover1760**
## About The Pull Request

Removes the whitelist for AIs, Posibrains, PAIs, non-head of staffs, police. (City council + The Judge is its own thing with the whitelist/election thing) as well as removes the player age restriction from antags. 

## Why It's Good For The Game

I wanna PoPo

All Tested locally, seems to work great even without any admin perms.

### CODE REVIEW

**Comment by murder357** [comment]
thank you blessed soul, we all needed this, maybe shady bob will stop selling crack to every department now

**Comment by genessee-forgot-his-password-again** [comment]
Holy shit I'm fucking braindead for missing this in the config, fuck

Thank you

**Comment by pitaden** [comment]
> thank you blessed soul, we all needed this, maybe shady bob will stop selling crack to every department now

why would I? now I have a new department to sell it to!

**Comment by genessee-forgot-his-password-again** [comment]
Test merged for Thursday. Ping me if you make commits after this so I can update the TM.

**Pull request merged**
